spring:
  datasource:
    url: jdbc:mysql://omdb-db:3306/omdb-db
#    url: jdbc:mysql://localhost:3307/omdb-db
    username: root
    password: haselko
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

consts:
  awardedTypeYes: "YES"
  awardedTypeTest: "TEST"
  categoryBestPicture: "Best Picture"
  omdbApiUrl: "https://www.omdbapi.com/"
  omdbApiTitleParamName: "t"
  omdbApiKeyParamName: "apikey"